GET http://localhost:8000/objeto

###
GET http://localhost:8000/objeto/6

###
DELETE http://localhost:8000/objeto/3

###
GET http://localhost:8000/objeto/2

###
GET http://localhost:8000/objeto?categoria_id=2
###
GET http://localhost:8000/objeto
###
GET http://localhost:8000/objeto?title=primer post4
###
GET http://localhost:8000/objeto?title=primer post4&categoria_id=2